spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.gnigbkbmhtbvhecdhcly
spring.datasource.password=kO0SW1tCTr8pTI5C

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ? JWT secret from env var ? must be at least 32 chars
jwt.secret=${JWT_SECRET:myhabittrackersecretkey1234567890abcdefghij}